# ============================================================
# MCUboot Bootloader Configuration (STM32H743IIT6)
# ============================================================

CONFIG_STM32_ENABLE_DEBUG_SLEEP_STOP=y

# --- Power Management ---
CONFIG_PM=n

# --- Stack ---
CONFIG_MAIN_STACK_SIZE=10240

# --- MCUboot Upgrade Strategy ---
CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n
CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_BOOTSTRAP=n

# --- Flash Driver ---
CONFIG_FLASH=y

# --- Logging ---
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PRINTK=y
CONFIG_CBPRINTF_NANO=y

# --- Console ---
CONFIG_UART_CONSOLE=y

# --- Use picolibc to reduce flash usage ---
CONFIG_PICOLIBC=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0

# --- Signature Verification ---
# ECDSA P256 + tinycrypt
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
CONFIG_BOOT_SIGNATURE_KEY_FILE="E:/zephyrproject/zephyr_workplace/test/mcuboot/keys/root-ec-p256.pem"
CONFIG_BOOT_ECDSA_TINYCRYPT=y
CONFIG_MCUBOOT_CLEANUP_ARM_CORE=n
